# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/messages/messages.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n protobuf/messages/messages.proto\x12\x08messages\"&\n\x08\x45nvelope\x12\x0c\n\x04type\x18\x01 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"\x1a\n\x07PingReq\x12\x0f\n\x07payload\x18\x01 \x01(\t\"\x1a\n\x07PingRes\x12\x0f\n\x07payload\x18\x01 \x01(\tB\x1cZ\x1asneakyfd/protobuf/messagesb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf.messages.messages_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\032sneakyfd/protobuf/messages'
  _ENVELOPE._serialized_start=46
  _ENVELOPE._serialized_end=84
  _PINGREQ._serialized_start=86
  _PINGREQ._serialized_end=112
  _PINGRES._serialized_start=114
  _PINGRES._serialized_end=140
# @@protoc_insertion_point(module_scope)
