// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: protobuf/messages/messages.proto

package messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          uint32                 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_protobuf_messages_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_messages_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_protobuf_messages_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Envelope) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PingReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       string                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingReq) Reset() {
	*x = PingReq{}
	mi := &file_protobuf_messages_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReq) ProtoMessage() {}

func (x *PingReq) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_messages_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReq.ProtoReflect.Descriptor instead.
func (*PingReq) Descriptor() ([]byte, []int) {
	return file_protobuf_messages_messages_proto_rawDescGZIP(), []int{1}
}

func (x *PingReq) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type PingRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       string                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRes) Reset() {
	*x = PingRes{}
	mi := &file_protobuf_messages_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRes) ProtoMessage() {}

func (x *PingRes) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_messages_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRes.ProtoReflect.Descriptor instead.
func (*PingRes) Descriptor() ([]byte, []int) {
	return file_protobuf_messages_messages_proto_rawDescGZIP(), []int{2}
}

func (x *PingRes) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

var File_protobuf_messages_messages_proto protoreflect.FileDescriptor

const file_protobuf_messages_messages_proto_rawDesc = "" +
	"\n" +
	" protobuf/messages/messages.proto\x12\bmessages\"2\n" +
	"\bEnvelope\x12\x12\n" +
	"\x04type\x18\x01 \x01(\rR\x04type\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"#\n" +
	"\aPingReq\x12\x18\n" +
	"\apayload\x18\x01 \x01(\tR\apayload\"#\n" +
	"\aPingRes\x12\x18\n" +
	"\apayload\x18\x01 \x01(\tR\apayloadB\x1cZ\x1asneakyfd/protobuf/messagesb\x06proto3"

var (
	file_protobuf_messages_messages_proto_rawDescOnce sync.Once
	file_protobuf_messages_messages_proto_rawDescData []byte
)

func file_protobuf_messages_messages_proto_rawDescGZIP() []byte {
	file_protobuf_messages_messages_proto_rawDescOnce.Do(func() {
		file_protobuf_messages_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_messages_messages_proto_rawDesc), len(file_protobuf_messages_messages_proto_rawDesc)))
	})
	return file_protobuf_messages_messages_proto_rawDescData
}

var file_protobuf_messages_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protobuf_messages_messages_proto_goTypes = []any{
	(*Envelope)(nil), // 0: messages.Envelope
	(*PingReq)(nil),  // 1: messages.PingReq
	(*PingRes)(nil),  // 2: messages.PingRes
}
var file_protobuf_messages_messages_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_messages_messages_proto_init() }
func file_protobuf_messages_messages_proto_init() {
	if File_protobuf_messages_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_messages_messages_proto_rawDesc), len(file_protobuf_messages_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_messages_messages_proto_goTypes,
		DependencyIndexes: file_protobuf_messages_messages_proto_depIdxs,
		MessageInfos:      file_protobuf_messages_messages_proto_msgTypes,
	}.Build()
	File_protobuf_messages_messages_proto = out.File
	file_protobuf_messages_messages_proto_goTypes = nil
	file_protobuf_messages_messages_proto_depIdxs = nil
}
